language: c

env: NOT_CRAN="true"

before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap

install:
- ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

after_script:
  - ./travis-tool.sh dump_logs

branches:
  only:
    - master
    - dev
    - adv-exp
